import { tildaCtaButton, tildaCtaLink } from "./tilda-cta";

interface ConsultationContactPopupOptions {
  basePath: string;
  telegramMeetingUrl: string;
  maxMeetingUrl: string;
}

// Canonical source: src/pages/index.astro → consultationContactPopupMarkup +
// consultationContactPopupAssets. SEO pages use its literal structure and
// behaviour; the only route-specific values are Telegram/MAX deep links.
export const renderConsultationContactPopup = ({
  basePath,
  telegramMeetingUrl,
  maxMeetingUrl,
}: ConsultationContactPopupOptions) => {
  const privacyPolicyUrl = `${basePath}privacy/`;
  const privacyConsentUrl = `${basePath}privacy/#consent`;
  const offerPageUrl = `${basePath}offer/`;

  return `<div id="consultation-contact-popup" class="tg-contact-popup" aria-hidden="true">
  <div class="tg-contact-popup__backdrop" data-consultation-popup-close></div>
  <div class="tg-contact-popup__panel" role="dialog" aria-modal="true" aria-labelledby="consultation-contact-title">
    <button class="tg-contact-popup__close" type="button" aria-label="Закрыть" data-consultation-popup-close></button>
    <div class="tg-contact-popup__content">
      <div>
        <p class="tg-contact-popup__eyebrow">Бесплатная встреча</p>
        <h2 id="consultation-contact-title">Выберите удобный способ</h2>
        <p class="tg-contact-popup__text">Напишите в Telegram или MAX, позвоните либо оставьте телефон, и я свяжусь с вами.</p>
        <div class="tg-contact-popup__links">
          ${tildaCtaLink("tg-contact-popup__link", telegramMeetingUrl, "Написать в Telegram", 'target="_blank" rel="nofollow" data-contact-channel="telegram"')}
          ${tildaCtaLink("tg-contact-popup__link", maxMeetingUrl, "Написать в MAX", 'target="_blank" rel="nofollow" data-contact-channel="max"')}
          ${tildaCtaLink("tg-contact-popup__link", "tel:+79253900772", "Позвонить", 'rel="nofollow" data-contact-channel="phone" data-contact-phone-reveal')}
        </div>
        <div class="tg-contact-popup__phone-card" data-contact-phone-card aria-hidden="false">
          <p class="tg-contact-popup__phone-label">Позвонить</p>
          <a class="tg-contact-popup__phone-number" href="tel:+79253900772">+7 925 390 07 72</a>
          <p class="tg-contact-popup__phone-note">На компьютере номер можно скопировать и набрать вручную.</p>
          <button class="tg-contact-popup__phone-copy" type="button" data-contact-phone-copy>Скопировать номер</button>
          <p class="tg-contact-popup__phone-status" data-contact-phone-status aria-live="polite"></p>
        </div>
        <p class="tg-contact-popup__hint">Можно выбрать любой удобный способ связи.</p>
      </div>
      <form class="tg-contact-popup__form" data-consultation-lead-form>
        <div class="tg-contact-popup__form-fields">
          <p class="tg-contact-popup__form-title">Оставить заявку</p>
          <input type="hidden" name="form_source" value="site_consultation_popup" />
          <label>Ваше имя *<input name="name" type="text" autocomplete="name" placeholder="Как к вам обращаться" required /></label>
          <label>Ваш телефон *<input name="phone" type="tel" inputmode="tel" autocomplete="tel" placeholder="+7 999 123-45-67" required /></label>
          <label>Комментарий<textarea name="comment" placeholder="Дата свадьбы, площадка или любой вопрос"></textarea></label>
          ${tildaCtaButton("tg-contact-popup__submit", "Отправить", "data-contact-submit")}
          <p class="tg-contact-popup__consent">Нажимая «Отправить», вы соглашаетесь с <a href="${privacyPolicyUrl}" target="_blank" rel="nofollow">политикой конфиденциальности</a>, <a href="${privacyConsentUrl}" target="_blank" rel="nofollow">согласием на обработку персональных данных</a> и <a href="${offerPageUrl}" target="_blank" rel="nofollow">условиями оферты</a>.</p>
          <p class="tg-contact-popup__status" data-contact-status></p>
        </div>
        <div class="tg-contact-popup__success" data-contact-success aria-live="polite">
          <span class="tg-contact-popup__success-icon" aria-hidden="true"></span>
          <p class="tg-contact-popup__success-title">Заявка отправлена</p>
          <p class="tg-contact-popup__success-text">Я свяжусь с вами в ближайшее время. Если хочется быстрее, можно написать сразу в Telegram.</p>
          ${tildaCtaLink("tg-contact-popup__success-link", telegramMeetingUrl, "Написать в Telegram", 'target="_blank" rel="nofollow"')}
        </div>
      </form>
    </div>
  </div>
</div>
<style>
  .tg-contact-popup{--t-headline-font:"Coolvetica",Arial,sans-serif;--t-text-font:"Manrope",Arial,sans-serif;position:fixed;inset:0;z-index:10020;display:none;align-items:center;justify-content:center;padding:28px;box-sizing:border-box;color:#1c1b1a}
  .tg-contact-popup.is-open{display:flex}.tg-contact-popup__backdrop{position:absolute;inset:0;background:rgba(28,27,26,.42);backdrop-filter:blur(10px)}
  .tg-contact-popup__panel{position:relative;z-index:1;width:min(920px,100%);max-height:min(760px,calc(100vh - 56px));overflow:auto;border-radius:12px;background:#fffefa;box-shadow:0 24px 80px rgba(28,27,26,.24)}
  .tg-contact-popup__close{position:absolute;top:18px;right:18px;z-index:2;width:42px;height:42px;border:1px solid rgba(28,27,26,.14);border-radius:50%;background:#fffefa;cursor:pointer}.tg-contact-popup__close::before,.tg-contact-popup__close::after{content:"";position:absolute;top:50%;left:50%;width:18px;height:2px;background:#1c1b1a;transform-origin:center}.tg-contact-popup__close::before{transform:translate(-50%,-50%) rotate(45deg)}.tg-contact-popup__close::after{transform:translate(-50%,-50%) rotate(-45deg)}
  .tg-contact-popup__content{display:grid;grid-template-columns:minmax(0,.95fr) minmax(280px,.7fr);gap:42px;padding:54px}.tg-contact-popup__eyebrow,.tg-contact-popup__text,.tg-contact-popup__hint,.tg-contact-popup__consent,.tg-contact-popup__form label,.tg-contact-popup__form input,.tg-contact-popup__form textarea,.tg-contact-popup__form button,.tg-contact-popup__link,.tg-contact-popup__success-link,.tg-contact-popup__status{font-family:var(--t-text-font,Arial);letter-spacing:0}
  .tg-contact-popup__eyebrow{margin:0 0 16px;color:#fa4604;font-size:18px;line-height:1.1}.tg-contact-popup h2{margin:0 48px 20px 0;color:#1c1b1a;font-family:var(--t-headline-font,Arial);font-size:64px;font-weight:500;line-height:1;text-transform:uppercase;letter-spacing:0}.tg-contact-popup__text{max-width:520px;margin:0 0 28px;color:rgba(28,27,26,.76);font-size:20px;line-height:1.24}
  .tg-contact-popup__links{display:grid;justify-items:start;gap:12px}.tg-contact-popup__link{width:max-content;min-width:clamp(200px,16.6667vw,320px);max-width:100%;--tg-cta-fill:#fffefa;--tg-cta-color:#1c1b1a;--tg-cta-arrow-fill:#fffefa;--tg-cta-arrow-color:#1c1b1a}.tg-contact-popup__hint{margin:14px 0 0;color:rgba(28,27,26,.52);font-size:14px;line-height:1.28}
  .tg-contact-popup .tg-tilda-cta{--tg-cta-height:30px;--tg-cta-arrow-box:30px;--tg-cta-overlap:1px;--tg-cta-pad-left:20px;--tg-cta-pad-right:18px;--tg-cta-radius:5px;--tg-cta-border:#fa4604;--tg-cta-icon-size:10px;--tg-cta-font-size:12px;position:relative;display:inline-grid;grid-template-columns:minmax(0,auto) calc(var(--tg-cta-arrow-box) - var(--tg-cta-overlap));align-items:stretch;min-height:0!important;height:var(--tg-cta-height)!important;padding:0!important;border:0!important;border-radius:0!important;box-sizing:border-box;background:transparent!important;color:var(--tg-cta-color)!important;font-family:var(--t-text-font);font-size:var(--tg-cta-font-size)!important;font-weight:400;line-height:1;text-decoration:none!important;background-image:none!important;transition:background-color .18s ease,color .18s ease,border-color .18s ease,box-shadow .18s ease,transform .18s ease;appearance:none;-webkit-appearance:none;cursor:pointer}.tg-contact-popup .tg-tilda-cta__plate,.tg-contact-popup .tg-tilda-cta__arrow-box{grid-row:1;border:1px solid var(--tg-cta-border);box-sizing:border-box;background:var(--tg-cta-fill);transition:background-color .18s ease,border-color .18s ease}.tg-contact-popup .tg-tilda-cta__plate{grid-column:1;min-width:0;border-radius:var(--tg-cta-radius)}.tg-contact-popup .tg-tilda-cta__arrow-box{grid-column:2;width:var(--tg-cta-arrow-box);margin-left:calc(-1 * var(--tg-cta-overlap));border-radius:var(--tg-cta-radius);background:var(--tg-cta-arrow-fill)}.tg-contact-popup .tg-tilda-cta__label{grid-column:1;grid-row:1;z-index:1;display:flex;align-items:center;justify-content:center;min-width:0;padding:0 var(--tg-cta-pad-right) 0 var(--tg-cta-pad-left);color:var(--tg-cta-color);font:inherit;line-height:1;white-space:nowrap;pointer-events:none}.tg-contact-popup .tg-tilda-cta__icon{grid-column:2;grid-row:1;z-index:1;display:grid;place-items:center;width:var(--tg-cta-arrow-box);margin-left:calc(-1 * var(--tg-cta-overlap));pointer-events:none}.tg-contact-popup .tg-tilda-cta__icon::before{content:"";width:var(--tg-cta-icon-size);height:var(--tg-cta-icon-size);background:var(--tg-cta-arrow-color);-webkit-mask:url("${basePath}images/tild3536-3939-4363-b163-323761323432__vector_8.svg") center / contain no-repeat;mask:url("${basePath}images/tild3536-3939-4363-b163-323761323432__vector_8.svg") center / contain no-repeat;transform:rotate(0);transform-origin:center;transition:transform .2s ease,background-color .18s ease}
  @media(min-width:1200px){.tg-contact-popup .tg-tilda-cta{--tg-cta-height:clamp(30px,2.5vw,48px);--tg-cta-arrow-box:clamp(30px,2.5vw,48px);--tg-cta-pad-left:clamp(20px,1.6667vw,34px);--tg-cta-pad-right:clamp(18px,1.5vw,26px);--tg-cta-radius:clamp(5px,.4167vw,8px);--tg-cta-icon-size:clamp(10px,.8333vw,16px);--tg-cta-font-size:clamp(12px,1vw,19px)}}@media(min-width:1920px){.tg-contact-popup .tg-tilda-cta{--tg-cta-height:48px;--tg-cta-arrow-box:48px;--tg-cta-pad-left:34px;--tg-cta-pad-right:26px;--tg-cta-radius:8px;--tg-cta-icon-size:16px;--tg-cta-font-size:19px}}@media(max-width:1199px){.tg-contact-popup .tg-tilda-cta{--tg-cta-height:35px;--tg-cta-arrow-box:35px;--tg-cta-pad-left:18px;--tg-cta-pad-right:16px;--tg-cta-radius:5px;--tg-cta-icon-size:13px;--tg-cta-font-size:13px}}@media(hover:hover){.tg-contact-popup .tg-tilda-cta:hover .tg-tilda-cta__icon::before{transform:rotate(45deg)}.tg-contact-popup__link:hover,.tg-contact-popup__success-link:hover{--tg-cta-fill:#fa4604;--tg-cta-color:#fffefa;--tg-cta-arrow-fill:#fa4604;--tg-cta-arrow-color:#fffefa;box-shadow:0 14px 28px rgba(250,70,4,.14);transform:translateY(-1px)}.tg-contact-popup__form button:hover{box-shadow:0 14px 28px rgba(250,70,4,.18);transform:translateY(-1px)}}
  .tg-contact-popup__phone-card{display:none;width:min(420px,100%);margin:14px 0 0}.tg-contact-popup.is-phone-visible .tg-contact-popup__phone-card{display:grid;gap:4px}@media screen and (min-width:1024px) and (pointer:fine){.tg-contact-popup__phone-card{display:grid;gap:0}.tg-contact-popup__link[data-contact-channel="phone"]{display:none}.tg-contact-popup__phone-label,.tg-contact-popup__phone-note,.tg-contact-popup__phone-copy,.tg-contact-popup__phone-status{display:none}}.tg-contact-popup__phone-label,.tg-contact-popup__phone-note,.tg-contact-popup__phone-copy,.tg-contact-popup__phone-status{font-family:var(--t-text-font,Arial);letter-spacing:0}.tg-contact-popup__phone-label{margin:0;color:rgba(28,27,26,.54);font-size:13px;line-height:1.2}.tg-contact-popup__phone-number{width:max-content;max-width:100%;color:#fa4604;font-family:var(--t-headline-font,Arial);font-size:34px;font-weight:500;line-height:1;text-decoration:none;letter-spacing:0;white-space:nowrap}.tg-contact-popup__phone-note{margin:4px 0 0;color:rgba(28,27,26,.64);font-size:14px;line-height:1.28}.tg-contact-popup__phone-copy{display:none;justify-self:start;min-height:38px;padding:0 14px;border:1px solid rgba(28,27,26,.16);border-radius:8px;background:#fffefa;color:#1c1b1a;font-size:14px;line-height:1;cursor:pointer}.tg-contact-popup__phone-status{display:none;min-height:16px;margin:0;color:rgba(28,27,26,.54);font-size:12px;line-height:1.25}
  .tg-contact-popup__form{display:grid;gap:10px;padding:18px;border:1px solid rgba(28,27,26,.12);border-radius:8px;background:#fffefa;align-content:start}.tg-contact-popup__form.is-sent{min-height:100%;align-content:center;padding:24px}.tg-contact-popup__form-fields{display:grid;gap:10px}.tg-contact-popup__form-title{margin:0 0 2px;color:#1c1b1a;font-family:var(--t-headline-font,Arial);font-size:34px;font-weight:500;line-height:1;text-transform:uppercase;letter-spacing:0}.tg-contact-popup__form label{display:grid;gap:6px;color:rgba(28,27,26,.62);font-size:13px;line-height:1.2}.tg-contact-popup__form input,.tg-contact-popup__form textarea{width:100%;min-height:48px;padding:0 14px;border:1px solid rgba(28,27,26,.18);border-radius:8px;box-sizing:border-box;background:#fffefa;color:#1c1b1a;font-size:16px;line-height:1.2;outline:0}.tg-contact-popup__form textarea{min-height:68px;padding-top:10px;resize:vertical}.tg-contact-popup__form input:focus,.tg-contact-popup__form textarea:focus{border-color:#fa4604}.tg-contact-popup__form button{justify-self:start;width:max-content;min-width:clamp(200px,16.6667vw,320px);max-width:100%;margin-top:2px;--tg-cta-fill:#fa4604;--tg-cta-color:#fffefa;--tg-cta-arrow-fill:#fa4604;--tg-cta-arrow-color:#fffefa}.tg-contact-popup__form button[disabled]{opacity:.74;cursor:wait}.tg-contact-popup__status{min-height:0;margin:0;color:rgba(28,27,26,.58);font-size:13px;line-height:1.25}.tg-contact-popup__consent{margin:2px 0 0;color:rgba(28,27,26,.52);font-size:12px;line-height:1.3}.tg-contact-popup__consent a{color:#1c1b1a;text-decoration:underline;text-underline-offset:2px}
  .tg-contact-popup__success{display:none;min-height:260px;align-content:center;justify-items:start;gap:14px}.tg-contact-popup__form.is-sent .tg-contact-popup__success{display:grid}.tg-contact-popup__form.is-sent .tg-contact-popup__form-fields{display:none}.tg-contact-popup__success-icon{position:relative;width:54px;height:54px;border-radius:50%;background:#fa4604;box-shadow:0 14px 32px rgba(250,70,4,.26);transform:scale(.88);animation:tgContactSuccessPop .36s cubic-bezier(.18,.89,.32,1.28) forwards}.tg-contact-popup__success-icon::after{content:"";position:absolute;left:18px;top:15px;width:17px;height:10px;border-left:3px solid #fffefa;border-bottom:3px solid #fffefa;transform:rotate(-45deg)}.tg-contact-popup__success-title{margin:0;color:#1c1b1a;font-family:var(--t-headline-font,Arial);font-size:38px;font-weight:500;line-height:1;text-transform:uppercase;letter-spacing:0}.tg-contact-popup__success-text{max-width:290px;margin:0;color:rgba(28,27,26,.66);font-family:var(--t-text-font,Arial);font-size:16px;line-height:1.28;letter-spacing:0}.tg-contact-popup__success-link{min-width:188px;margin-top:6px;--tg-cta-fill:#fffefa;--tg-cta-color:#1c1b1a;--tg-cta-arrow-fill:#fffefa;--tg-cta-arrow-color:#1c1b1a}@keyframes tgContactSuccessPop{to{transform:scale(1)}}body.tg-contact-popup-open{overflow:hidden!important}
  @media screen and (max-width:1199px){.tg-contact-popup__content{grid-template-columns:1fr;gap:30px;padding:44px}.tg-contact-popup h2{font-size:54px}}@media screen and (max-width:639px){.tg-contact-popup{padding:12px;align-items:flex-end}.tg-contact-popup__panel{max-height:calc(100vh - 24px);border-radius:10px}.tg-contact-popup__content{gap:24px;padding:34px 18px 20px}.tg-contact-popup__close{top:10px;right:10px;width:36px;height:36px}.tg-contact-popup__eyebrow{font-size:15px}.tg-contact-popup h2{margin-right:36px;font-size:38px}.tg-contact-popup__text{font-size:16px;line-height:1.28}.tg-contact-popup__link{width:max-content;min-width:min(300px,100%);max-width:100%;grid-template-columns:minmax(0,1fr) calc(var(--tg-cta-arrow-box) - var(--tg-cta-overlap));--tg-cta-pad-left:14px;--tg-cta-pad-right:12px}.tg-contact-popup__phone-card{width:100%;margin-top:14px}.tg-contact-popup__phone-number{font-size:28px}.tg-contact-popup__form button{justify-self:start;width:max-content;min-width:min(300px,100%);max-width:100%}.tg-contact-popup__form{padding:14px}.tg-contact-popup__form.is-sent{min-height:300px;padding:20px}.tg-contact-popup__success-title{font-size:32px}.tg-contact-popup__consent{font-size:11px}.tg-contact-popup__form-title{font-size:28px}}
</style>
<script>
  (function(){
    var popupId='consultation-contact-popup';var openSelector='[data-consultation-popup-open]';var desktopPhoneQuery=window.matchMedia?window.matchMedia('(min-width:1024px) and (pointer:fine)'):null;var endpoint=/^(localhost|127\\.0\\.0\\.1)$/.test(window.location.hostname)?'http://127.0.0.1:8000/api/v1/site/consultation-request':'https://calcul.timurgromov.ru/api/v1/site/consultation-request';
    function getPopup(){return document.getElementById(popupId)}function isDesktopPhoneMode(){return !!(desktopPhoneQuery&&desktopPhoneQuery.matches)}function setStatus(form,text){var status=form&&form.querySelector('[data-contact-status]');if(status)status.textContent=text||''}function setPhoneStatus(popup,text){var status=popup&&popup.querySelector('[data-contact-phone-status]');if(status)status.textContent=text||''}function setTildaCtaLabel(button,text){var label=button&&button.querySelector('[data-tilda-cta-label]');if(label)label.textContent=text;else if(button)button.textContent=text}
    function resetPhoneCard(popup){if(!popup)return;popup.classList.remove('is-phone-visible');var card=popup.querySelector('[data-contact-phone-card]');if(card)card.setAttribute('aria-hidden',isDesktopPhoneMode()?'false':'true');setPhoneStatus(popup,'')}function resetLeadForm(popup){var form=popup&&popup.querySelector('[data-consultation-lead-form]');var button=form&&form.querySelector('[data-contact-submit]');if(!form)return;form.classList.remove('is-sent');setStatus(form,'');if(button){button.disabled=false;button.classList.remove('is-loading');setTildaCtaLabel(button,'Отправить')}}function openPopup(event){if(event)event.preventDefault();var popup=getPopup();if(!popup)return;resetLeadForm(popup);resetPhoneCard(popup);popup.classList.add('is-open');popup.setAttribute('aria-hidden','false');document.body.classList.add('tg-contact-popup-open')}function closePopup(){var popup=getPopup();if(!popup)return;popup.classList.remove('is-open');popup.setAttribute('aria-hidden','true');resetPhoneCard(popup);document.body.classList.remove('tg-contact-popup-open')}
    function normalizePhoneForSubmit(value){var raw=String(value||'').trim();if(!raw)return '';var digits=raw.replace(/\\D/g,'');if(!digits)return raw;if(digits.length===11&&digits.charAt(0)==='8')digits='7'+digits.slice(1);return '+'+digits}
    document.addEventListener('click',function(event){var opener=event.target&&event.target.closest&&event.target.closest(openSelector);if(opener){openPopup(event);return}var phoneRevealer=event.target&&event.target.closest&&event.target.closest('[data-contact-phone-reveal]');if(phoneRevealer&&isDesktopPhoneMode()){event.preventDefault();return}var phoneCopy=event.target&&event.target.closest&&event.target.closest('[data-contact-phone-copy]');if(phoneCopy){event.preventDefault();var popup=getPopup();var phoneText='+7 925 390 07 72';if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(phoneText).then(function(){setPhoneStatus(popup,'Номер скопирован.')}).catch(function(){setPhoneStatus(popup,phoneText)})}else setPhoneStatus(popup,phoneText);return}var closer=event.target&&event.target.closest&&event.target.closest('[data-consultation-popup-close]');if(closer){event.preventDefault();closePopup()}});document.addEventListener('keydown',function(event){if(event.key==='Escape')closePopup()});
    document.addEventListener('submit',function(event){var form=event.target&&event.target.closest&&event.target.closest('[data-consultation-lead-form]');if(!form)return;event.preventDefault();var button=form.querySelector('[data-contact-submit]');var formData=new FormData(form);var tracking=typeof window.tgGetTrackingBundle==='function'?window.tgGetTrackingBundle():{yclid:null,campaign_params:{}};var payload={name:String(formData.get('name')||'').trim(),phone:normalizePhoneForSubmit(formData.get('phone')),comment:String(formData.get('comment')||'').trim(),form_source:String(formData.get('form_source')||'site_consultation_popup').trim(),page_url:window.location.href,yclid:tracking.yclid,campaign_params:tracking.campaign_params,attribution_context:tracking.attribution_context};if(!payload.name||!payload.phone){setStatus(form,'Укажите имя и телефон.');return}setStatus(form,'Отправляю...');if(button){button.disabled=true;button.classList.add('is-loading');setTildaCtaLabel(button,'Отправляем...')}fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload),credentials:'omit'}).then(function(response){if(!response.ok)throw new Error('consultation request failed');if(typeof window.ym==='function'&&window.mainMetrikaId)window.ym(window.mainMetrikaId,'reachGoal','site_consultation_submit_success');form.reset();setStatus(form,'');form.classList.add('is-sent')}).catch(function(){setStatus(form,'Не удалось отправить форму. Лучше написать в Telegram или MAX.');if(button){button.disabled=false;button.classList.remove('is-loading');setTildaCtaLabel(button,'Отправить')}}).finally(function(){if(button&&!form.classList.contains('is-sent')){button.disabled=false;button.classList.remove('is-loading');setTildaCtaLabel(button,'Отправить')}})});
  }());
</script>`;
};
